Ext.define('Sgai.model.su.user.User',
    {
        extend: 'Ext.data.Model',
        autoLoad: true,
        fields: [
            {name: 'sid' , type: 'int', useNull:true,critical:true},               
            {name: 'pin' , type: 'string'},  
            {name: 'userNameCn', type: 'string'},
            {name: 'userNameEn', type: 'string'},
            {name: 'userNameVn', type: 'string'},           
            {name: 'country', type: 'int'},
            {name: 'sex', type: 'string'},
            {name: 'password', type: 'string'},
            {name: 'email', type: 'string'},
            {name: 'extTel', type: 'string'},
            {name: 'phone1', type: 'string'},
            {name: 'phone2', type: 'string'},
            {name: 'deptCode', type: 'string'},
            {name: 'groupId', type: 'string'},
            {name: 'shiftId', type: 'string'},
            {name: 'passModifyDate', type: 'date'},
            {name: 'state', type: 'int'},
            {name: 'createdBy', type: 'string'},
            {name: 'createdTimestamp', type: 'date'},
            {name: 'updateBy', type: 'string'},
            {name: 'updateTimestamp', type: 'date'},
            {name: 'version', type: 'int',critical:true},
            {name: 'userSecurityRoles', type: 'string'},
            {name: 'shortName', type: 'string'},
            {name: 'branchCompanyId', type: 'string'},
            {name: 'workshopId', type: 'string'},
            {name: 'userGroupNames', type: 'string'},
            {name: 'roleNames', type: 'string'}
        ]
    });
